version: '3.4'

services:
  reselect:
    image: reselect
    build:
      context: src/stable/src/vs/workbench/libraries/reselect-master/reselect-master
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
