name: Sweep Issue
title: 'Sweep: '
description: Handle bugs, features, and refactors related to the workbench integration in CodeCurse.
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: Provide specific details and context about the desired changes or improvements related to the workbench integration.
      placeholder: |
        Unit Tests: Write unit tests for workbench integrations in <FILE>. Ensure comprehensive coverage, especially for critical components.
        Bugs: Investigate any issues in the workbench integrations located in <FILE>. Refer to the logs and documentation for more context.
        Features: Enhance the workbench integrations by implementing new features or optimizing existing ones. Consider using classes or methods from <FILE> if relevant.
        Refactors: Consider refactoring or optimizing the workbench integrations. If migrating or updating any functions, ensure compatibility with the rest of the workbench components.
